name: dlang
version: v2.084.0
summary: D language
base: core18
description: |
  D is a general-purpose programming language with static typing, systems-level access, and C-like syntax. With the D Programming Language, write fast, read fast, and run fast. 
  Fast code, fast.
  This snap is maintained by Ernesto Castellotti, and is not necessarily endorsed or officially maintained by the upstream developers.
  
confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: i386

environment:
  PATH: $PATH:$SNAP/usr/bin
  CC: $SNAP/usr/bin/gcc --sysroot=$SNAP

slots:
  dlang:
    interface: content
    read:
      - $SNAP/etc
      - $SNAP/lib
      - $SNAP/lib64
      - $SNAP/usr
apps:
  catdoc:
    command: usr/bin/catdoc
    plugs:
      - home
  changed:
    command: usr/bin/changed
    plugs:
      - home
      - network
  checkwhitespace:
    command: usr/bin/checkwhitespace
    plugs:
      - home
  contributors:
    command: usr/bin/contributors
    plugs:
      - home
  dcd-client:
    command: usr/bin/dcd-client
    plugs:
      - home
      - network
  dcd-server:
    command: usr/bin/dcd-server
    plugs:
      - home
      - network
      - network-bind
  ddemangle:
    command: usr/bin/ddemangle
    plugs:
      - home
  detab:
    command: usr/bin/detab
    plugs:
      - home
  dfmt:
    command: usr/bin/dfmt
    plugs:
      - home
  dget:
    command: usr/bin/dget
    plugs:
      - home
  dmd:
    command: usr/bin/dmd -conf=/snap/dlang/current/etc/dmd.conf
    plugs:
      - home
  dscanner:
    command: usr/bin/dscanner
    plugs:
      - home
  dub:
    command: usr/bin/dub
    plugs:
      - home
      - network
  dustmite:
    command: usr/bin/dustmite
    plugs:
      - home
  rdmd:
    command: usr/bin/rdmd
    plugs:
      - home
  tolf:
    command: usr/bin/tolf
    plugs:
      - home
  
parts:
  dlang-all:
    plugin: nil
    after:
      - dmd
      - dmd-config
      - druntime
      - libphobos
      - dlang-docs
      - dtools
      - dub
      - dcd
      - dscanner
      - dfmt     
